### ISSUE TITLE
Code showing error

### ISSUE THREAD

**Issue by MyOnAsSalat** [aspnet/AspNetCore.Docs.ru-ru#50]
Code in code block are covered by yellow lines, it make some lines of code on this page invisible.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: ed756b9c-1d37-cd29-dbca-2838ddf152fb
* Version Independent ID: 06064983-8ada-c25d-2adc-ffb4059978f2
* Content: [Внедрение зависимостей в представления в ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/mvc/views/dependency-injection?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/views/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/mvc/views/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #13186](https://github.com/aspnet/AspNetCore.Docs/issues/13186) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @MyOnAsSalat 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/13186

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
